services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.shadow-cljs
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  app-prod:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    profiles:
      - production